import os

CLOUDBURST_USERNAME = os.getenv("CLOUDBURST_USERNAME")
CLOUDBURST_PASS = os.getenv("CLOUDBURST_PASS")
CLOUDBURST_HOST = os.getenv("CLOUDBURST_HOST")
SSH_PRIVATE_KEY_PASSWORD = os.getenv("SSH_PRIVATE_KEY_PASSWORD")
SSH_PKEY = os.getenv("SSH_PKEY")
